### ISSUE TITLE
Profit is not tracking properly

### ISSUE THREAD

**Issue by brads93** [wikiworm/InventoryValue#15]
-Profit (inv) goes negative when using bank deposit box
-Profit (banked) is not tracking with bank deposit box, stays at 0 
-Uncut gems that automatically go into an open Gem Bag are not tracked
Otherwise love the concept as you seem to be the most recently active person working on an inventory profit tracker. Be great to have an hourly counter as well :D Thanks!

**Comment by wikiworm** [comment]
Glad you like the plugin! Thanks for the feed back -- I will investigate these and get back to you. 

I will have a new release with support for the rune pouch, herb sack, seed box, gem bag, and coal bag. If there are any other containers you'd like to see tracked please let me know.

**Comment by wikiworm** [comment]
So, I've started work on this. Here is my update so far. 

Inventory item containers have no event hooks, so, the profit calculation is actually quite tricky. This is because I have to manually introspect on the contents of the container, find the value of each item in the container, find the contents of the value in each container, add them up, and return the value. I have RunePouch completed. I also have herb sack finished -- but there's a catch. 

For the herb sack, seed box, gem bag, coal bag, looting bag, essence pouch, etc. (i.e. any inventory container with the exception of the RunePouch) there's currently no way to introspect on the contents of the container. [There's a thread on the RuneLite issues page that details this regarding essence pouches.](https://github.com/runelite/runelite/issues/6376). 

So, the way to deal with the contents of these inventory containers is to have the user issue the "Check" menu option. This prints the contents of the container to the chat. I save up some state about whats in the bag and during an inventory value calculation, check the value of the contents.

Alternatively, I could watch the chat messages for the appropriate "You put it straight into..." message. However, this will only work for players who use the container while it's open and I have to explicitly track the previous message to know which gem/herb/seed etc. was put into the container. The problem with this approach is that it's possible to miss "what" was put into the container unless I keep a rolling buffer of messages -- which is not desirable and the PluginHub moderators may not support that decision. 

So, that's inventory containers. I'll eventually get to them all, but will release a first pass with only support for herb sack, gem bag, and seed box. 

Once I finish the following containers -- gem bag, seed box, herb sack -- I'll work on the deposit box problem. This is an outstanding issue that has been bugging me for awhile as I'm currently at MLM and my own plugin doesn't work as expected :)  

Feel free to use the code in the dev branch to test out herb sack and rune pouch.

**Comment by wikiworm** [comment]
Alright. One more update. I've added rune pouch, gem bag, herb sack, and seed box. I'll do a little bit more play testing and then start working on the deposit box.

**Comment by wikiworm** [comment]
Everything I promised in the update is now added in the dev branch. I have rune pouch, gem bag, herb sack, and seed box. I also have deposit box/pool etc. working as well.

I also added a "reset" command. This is hopefully a catchall in case there's an edge case I've missed. So, if you ever see weird/unexpected numbers in the profit calculation, you can run the command "!Reset_iv" which will reset the inventory value and bank profit calculations. 

I'm going to play with this today to make sure I don't find any bugs. Pending any feed back, I'll close this issue and publish a release tomorrow. 

Once again, thanks for your report @brads93 -- these are some great features.

**Comment by wikiworm** [comment]
These changes are now public. I'll go ahead and close this issue.
