### ISSUE TITLE
Plugin not available on Runelite, needs update

### ISSUE THREAD

**Issue by vbojilov** [wikiworm/InventoryValue#9]
It appears the plugin has been pulled from Runelite (not available anymore) as of May 18, 2022 due to needing what I assume are compatibility updates with current client versions. Is this something we can resolve? I always miss this super useful tool!

**Comment by wikiworm** [comment]
Sorry to hear that it's missing from plugin hub! Thanks for letting me know. I'll take a look and see what it takes to republish the plugin. Due to the holiday weekend (in the US), I will not have access to my normal PC and it may take a few days to resolve.

I'll close this issue when the plugin is republished.

**Comment by wikiworm** [comment]
This issue is addressed as of PR [2948](https://github.com/runelite/plugin-hub/commit/5f35dcb24dbbfd9248c497d680dc41ab8f68ae87). Thanks for reporting this. I'll close the issue.

**Comment by vbojilov** [comment]
Thank you so much! You're the absolute best!
